name: MoontrixLogin
authors: [Lordmoontrix]
website: https://github.com/schooldevontop/MoontrixLogin
description: Secure authentication plugin for Bukkit-based servers.
main: fr.lordmoontrix.moontrixlogin.MoontrixLogin
version: 1.0.0
api-version: 1.21
softdepend:
    - Vault
    - LuckPerms
    - PermissionsEx
    - bPermissions
    - zPermissions
    - Multiverse-Core
    - Essentials
    - EssentialsSpawn
    - ProtocolLib
commands:
  moontrixlogin:
    description: MoontrixLogin core command
    usage: /moontrixlogin
    aliases:
    - moontrix
    - mlogin
  email:
    description: Manage email and recover passwords
    usage: /email show|add|change|recover|setpassword
  login:
    description: Log in to your account
    usage: /login <password> [totp]
    aliases:
    - l
    - log
  logout:
    description: Log out of your session
    usage: /logout
  register:
    description: Register a new account
    usage: /register [password] [verifyPassword]
    aliases:
    - reg
  unregister:
    description: Delete your account
    usage: /unregister <password>
    aliases:
    - unreg
  changepassword:
    description: Change your password
    usage: /changepassword <oldPassword> <newPassword>
    aliases:
    - changepass
    - cp
  totp:
    description: Two-factor authentication (TOTP)
    usage: /totp code|add|confirm|remove
    aliases:
    - 2fa
  captcha:
    description: Captcha verification
    usage: /captcha <captcha>
  verification:
    description: Verify email by code
    usage: /verification <code>
permissions:
  moontrixlogin.player.*:
    description: All MoontrixLogin player permissions
    children:
      moontrixlogin.player.captcha: true
      moontrixlogin.player.changepassword: true
      moontrixlogin.player.email.add: true
      moontrixlogin.player.email.change: true
      moontrixlogin.player.email.recover: true
      moontrixlogin.player.email.see: true
      moontrixlogin.player.login: true
      moontrixlogin.player.logout: true
      moontrixlogin.player.register: true
      moontrixlogin.player.security.verificationcode: true
      moontrixlogin.player.totpadd: true
      moontrixlogin.player.totpremove: true
      moontrixlogin.player.unregister: true
  moontrixlogin.player.captcha:
    description: Complete captcha challenges
    default: true
  moontrixlogin.player.changepassword:
    description: Change own password
    default: true
  moontrixlogin.player.email:
    description: Email-related permissions
    children:
      moontrixlogin.player.email.add: true
      moontrixlogin.player.email.change: true
      moontrixlogin.player.email.recover: true
      moontrixlogin.player.email.see: true
  moontrixlogin.player.email.add:
    description: Add email address
    default: true
  moontrixlogin.player.email.change:
    description: Change email address
    default: true
  moontrixlogin.player.email.recover:
    description: Recover password via email
    default: true
  moontrixlogin.player.email.see:
    description: View own email
    default: true
  moontrixlogin.player.login:
    description: Login to the server
    default: true
  moontrixlogin.player.logout:
    description: Logout from the server
    default: true
  moontrixlogin.player.register:
    description: Register an account
    default: true
  moontrixlogin.player.security.verificationcode:
    description: Verify email with code
    default: true
  moontrixlogin.player.totpadd:
    description: Enable TOTP
    default: true
  moontrixlogin.player.totpremove:
    description: Disable TOTP
    default: true
  moontrixlogin.player.unregister:
    description: Unregister account
    default: true

